### ISSUE TITLE
Getting more info in the members/api resplose

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#109]
@XertroV When hilling "https://api.blockchain.suzuka.flux.party/members/api" with `'method': 'ballot_publish'`

Could I get more back than just the `billCreationTxid`? It would be good to also get the: 

- ballotID `Int` 
- blockNo

**Comment by XertroV** [comment]
Addendum: when moving quickly like we are, the only real "hard no" type thing to implementation is _unsafe architecture_ (which would also have highest techdebt). Like relying on the API returning things could mean _lots_ of refactoring later.

The way the system _should_ work from a redux-esq PoV: (at least this is how I've done it)
1. Load democ-level parameters (index address, democ hash, etc) _so the mutation / data added to state would look like: =>_ `{_networkParams: NetworkParams}`
2. Enumerate ballots => `{specHashes: Set<bytes32>}`
3. Get details of each ballot => `{ballotSpecs: Dictionary<bytes32, BallotSpec>}`

**Comment by KipCrossing** [comment]
Looks like `hexlify` doesn't take `str`:

```
Error pushing to chain: a bytes-like object is required, not 'str'

['  File "/home/kipling/Programs/voting-app-api/update_ballotspecs_db.py", line 75, in update_ballotspecs\n    "specHash": render_spec_hash(id),\n', '  File "/home/kipling/Programs/voting-app-api/update_ballotspecs_db.py", line 69, in render_spec_hash\n    return "0x" + ("00" * (32 - len(_s)) + hexlify(_s).decode(\'ascii\'))\n']

CONTINUING
```
