### ISSUE TITLE
List all proposals from blockchain

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#112]

**Comment by XertroV** [comment]
This should probably be "load all proposals from blockchain to state"

**Comment by KipCrossing** [comment]
You've embarrassed me!

**Comment by KipCrossing** [comment]
@bazmatic here is an endpoint:

https://1j56c60pb0.execute-api.ap-southeast-2.amazonaws.com/dev/spec

With all the spec info.
