### ISSUE TITLE
Micro-Service approach

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#12]
# Micro-Service approach

During discussions with @oscarmanderj and @ptboyer about the project flow, it was suggested to go with a microservice approach; small manageable repos, instead of 1 or 2 big ugly ones. This discussion issue is here to facilitate a conversation regarding the ethos we will use when deciding the scope of each microservice project. 

An expected outcome of using this approach is that smaller repos can be managed (owned) by different devs, and they can make their own decisions on the implementation. A good example of this is my [Aus-Bills](https://github.com/KipCrossing/Aus-Bills) project which is a python package that can be installed using pip; see [ausbills](https://pypi.org/project/ausbills/). A microservice that manages the DB would use this, for instance. 

---

### Use CI/CD 

I use [CirceCI](https://circleci.com/), it could be good to use the same for all.

**CI,** once other services are using yours, don't change your tests unless adding to them (eg new method for something new). 

**CD** to automate the integration of new features.

*Talk to the team if major changes are changed and tests are changed*

### Package if Possible

Imagine that your service could be used by something else other than the app, how would you go about structuring it, packaging it and publishing it?

*Not for all services:* in this case your CD should push changes to the project, not a package index.

### Don't make them too small

It would be over the top to, for example, have separate repos for each lambda function. We should try put these under one repo with a unifying theme (eg language). 

### Documentation 

Write a good README with **Usage** instructions and **Contributing** guidelines/setup. Tell us the purpose of the repo.

---

These are just my thoughts, input would be nice :)

**Comment by KipCrossing** [comment]
We should have a unifying place for all this; perhaps an organisation or "Awesome" file. Suggestions?

**Comment by ptboyer** [comment]
I agree, let's use CircleCI. It's gotta be faster than other (free) runners I've used.

When it comes to packages and services, realistically there are only:

- App/Client (not a service)
- Serverless Lambdas (distributed service)
- Blockchain contract (distributed service also)

So, I'm not really sure what the main discussion points are for this particular issue moving forward.

**Comment by KipCrossing** [comment]
The other services to consider are:

- Update DB with new bills
- Update DB with new issues (Simple admin portal)
- Verification against the AEC

Even the app can be broken down into different Flutter Packages; say one that handles all the voting; with widgets for different types of voting (binary, preference, IBDD...)

Perhaps I'm being a bit liberal with the term "Service", but the point still stands. The idea is that someone may take initiative on an element of the stack that needs a dong and own it, in terms of direction and implementation; as long as the docs are written well for integration.

**Comment by sventhebarbarian** [comment]
I am a fan of microservices, one way I would look at it, like mentioned, is are there any parts of the design that might be used in other applications.

If the flow is small it might not be needed to split into services, but eg the bill scraper could definitely be split into its own service, which then feeds the BlockChainEnv/Bill Database.

The BlockchainEnv could probably be abstracted out into its own service.

I understand the Bill Database maintains additional info that is not stored in the blockchain? Is the blockchain only used for basic ids/vote recording while the Bill Database keeps the presentation info for all the bills? If that is the case the blockchainEnv could almost be a use-case agnostic service, feed in an id, manage votes, report tallies .. for any situation

**Comment by sventhebarbarian** [comment]
> The other services to consider are:
> 
> * Update DB with new bills
> * Update DB with new issues (Simple admin portal)
> * Verification against the AEC
> 
Agreed, each being self contained, so Bills is one service with its own database, Issues is another, if these are being combined into a single list of "things to vote on" maybe have a third service that collates them (and could collate other structures into a single dataset).

Verification against AEC - definitely another service, because could be used by other projects in other use cases..

**Comment by KipCrossing** [comment]
> I understand the Bill Database maintains additional info that is not stored in the blockchain? 

Yes that's correct. Only some crucial data will go into the balotspec to be hashed for the blockchain. The rest may change. eg the addition of a third reading.

**Comment by sventhebarbarian** [comment]
I would also suggest the interaction with the blockchain is abstracted, possibly into its own service, so you could easily switch to other storage systems/blockchains but maintain the single BlockChainEnv which manages communication with App/requests from bill scraper etc..
