### ISSUE TITLE
Unexpected highlighting of search term

### ISSUE THREAD

**Issue by connorhsm** [voteflux/voting_app#133]
When typing in the search bar, text is being highlighted unexpectedly. I believe the highlight is caused by autocorrect. It is in a very different style than what feels natural and makes me feel that the next letter I type would be replacing the highlighted text.
![ezgif-5-6ad9cca5c15f](https://user-images.githubusercontent.com/20902771/91146778-b15b8900-e6fa-11ea-9347-107a72acb2b0.gif)

**Comment by KipCrossing** [comment]
Could no reproduce
