### ISSUE TITLE
Baron Update

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#141]
* could sense there was a stronger demand for UI bashing sooner rather than later, rather than a lot of testing or a longer research phase
* want to have something to show something for last sat but not happy, hopefully by this week
* essentially what's there in a low fi system + a few mockups in higher fidelity
* good flow through of the app, get feedback from "stakeholders"
* logo and branding
* RB: we can do some drafts and see what ppl think
* insofar as the logo: no typeface, some work needed, not very identifiable (can't see the D and P in the logo)
* visibility of name in logo not there

**Comment by XertroV** [comment]
RB: need assets or direction, don't want to waste work; want to avoid re-going over that stuff

**Comment by KipCrossing** [comment]
#142
