### ISSUE TITLE
UI UX design and basic branding

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#142]
MK:

* too late to change name
* not on critical path
* unless there's a big problem with the name we shouldn't change before WA election
* should carry name through WA election - can change branding after that

RB:

* once we have a more polished UI we might get come incidental issues

**Comment by XertroV** [comment]
RB: 

* if ~everyone hated the name we should change, but hard to know explanatory reasons; risky to act too quickly (e.g. out of fear). Better to find out proper underlying reason and address that problem

**Comment by RedBaron2104** [comment]
Updated logo and palette below. The new "Digi-Green" (The colour of the D in the Digipol symbol) has a stronger contrast to and visibility/legibility on white but still looks excellent in our midnight shades, dark colour scheme.

In other news we're also wanting to update the app font from Helvetica to Montserat. This will be showcased in our upcoming mid-fi iteration.

![Digipol-Logo](https://user-images.githubusercontent.com/68624164/92993763-9fba1400-f537-11ea-8403-808759f998c6.png)
![Digipol-Logo-White](https://user-images.githubusercontent.com/68624164/92993764-a052aa80-f537-11ea-8281-3fca45959a6f.png)
![Digipol-Palette](https://user-images.githubusercontent.com/68624164/92993765-a0eb4100-f537-11ea-93dd-c84d91b7741b.png)

**Comment by oscarmanderj** [comment]
Love it

**Comment by KipCrossing** [comment]
https://xd.adobe.com/view/59df9aaa-9c2b-4d61-b839-5ea133aa39ec-0c8c/?fullscreen&hints=off

**Comment by KipCrossing** [comment]
Comments by @oscarmanderj  :

nice work, aesthetics are great.

nice work, aesthetics are great.

**Feed back**
- Colour scheme is great, can you do a light mode?
- I think the navbar should be on the bottom, closer to your thumb
- I think there needs to be representation of the amount of votes on the cards.
- 'open' text is too bright for me. Is it necessary?
- Would a slightly roundish serif font be better for the main headings? Something a bit more "documenty". Gives more contrast between heading and text.

Some other UI design stuff, but I think that will get polished out and will not go into it.

Just my 2c

**Comment by KipCrossing** [comment]
Closed in release 0.2.0
