### ISSUE TITLE
RedBaron to upload pdf or something of app/preso/whatever - design docs

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#144]

**Comment by RedBaron2104** [comment]
[Digipol-wireframe-01.pdf](https://github.com/voteflux/voting_app/files/5207603/Digipol-wireframe-01.pdf)

This is the _first draft_ of the app uplift. We are still working on the categories and achievements. Feel free to provide feedback!

**Comment by KipCrossing** [comment]
Nice!

**Comment by RedBaron2104** [comment]
Hi everyone please find the mid-fi draft here
[Digipol_Mid-Fi_Draft.pdf](https://github.com/voteflux/voting_app/files/5254809/Digipol_Mid-Fi_Draft.pdf)

**Comment by oscarmanderj** [comment]
nice work, aesthetics are great.

**Feed back**
- Colour scheme is great, can you do a light mode?
- I think the navbar should be on the bottom, closer to your thumb
- I think there needs to be representation of the amount of votes on the cards.
- 'open' text is too bright for me. Is it necessary?
- Would a slightly roundish serif font be better for the main headings? Something a bit more "documenty". Gives more contrast between heading and text.

Some other UI design stuff, but I think that will get polished out and will not go into it.

Just my 2c

**Comment by XertroV** [comment]
#142 #141 (related)

**Comment by XertroV** [comment]
@RedBaron2104 I just noticed there aren't any results in mockups

**Comment by KipCrossing** [comment]
Merging discussion with #142
