### ISSUE TITLE
DigiPol & Flux UI/UX design mock-ups 10/20 - 03/21

### ISSUE THREAD

**Issue by RedBaron2104** [voteflux/voting_app#150]
This will be the central repo for mock-up version control.

**Comment by RedBaron2104** [comment]
[Digipol_Mid-Fi_Draft.pdf](https://github.com/voteflux/voting_app/files/5369314/Digipol_Mid-Fi_Draft.pdf)

21/09 version. Planning for update by 19/10.

**Comment by RedBaron2104** [comment]
03/10 version

https://xd.adobe.com/view/317f1871-dcc3-4ba4-b9ee-79862e4b858a-642c/?fullscreen&hints=off

**Comment by RedBaron2104** [comment]
18/10 version aka v181020

https://xd.adobe.com/view/317f1871-dcc3-4ba4-b9ee-79862e4b858a-642c/?fullscreen&hints=off

**Comment by KipCrossing** [comment]
Nice one @RedBaron2104 

Do you have somewhere you are keeping the assets for this? eg the robot people

**Comment by RedBaron2104** [comment]
Sorry that was the wrong link, it's been updated now. The illustrations on the intro slides are stock images so we will need to take some time to get a budget for acquiring images or for custom illustrations, in the meantime they can be removed and it can just be the gradient. The only other thing will be the icons which I will upload shortly - I need some specifications around that in case the source file images are too small or something.

**Comment by KipCrossing** [comment]
When the time comes, I'll teach you how to add assets to the https://github.com/voteflux/voting_app/tree/master/assets dir.

Once done, and your PR is approved, you'll be recognised in the contributers list.

**Comment by KipCrossing** [comment]
Merging this discussion with #142
