### ISSUE TITLE
Onboarding slides

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#161]
Refactor on Boarding slides according to:
https://xd.adobe.com/view/59df9aaa-9c2b-4d61-b839-5ea133aa39ec-0c8c/?fullscreen&hints=off
https://docs.google.com/presentation/d/1WpOQDLw-KJUEdW4-2kJSFpRewSjSKCc3XlGtjc0tXLY/edit#slide=id.p

**Comment by RedBaron2104** [comment]
Ready to make a change? -
https://www.shutterstock.com/image-vector/people-holding-vote-banners-woman-speaker-1557295766

Send a message directly to politicians -
https://www.shutterstock.com/image-vector/political-meeting-candidate-voting-speech-preelection-1427167982

Your decisions are secure and final -
https://www.shutterstock.com/image-vector/set-businesspeople-catching-money-net-businesswoman-1549440341

Hear from your community -
https://www.shutterstock.com/image-vector/web-software-development-business-meeting-start-1445314298

Have your say on what’s important to you -
https://www.shutterstock.com/image-vector/election-social-poll-concept-tiny-voters-1837725313
(although might not need an image for this slide as there are tags to choose?)

**Comment by KipCrossing** [comment]
Cool! I've shared with @thatwasmycat

**Comment by KipCrossing** [comment]
Done in #174
