### ISSUE TITLE
Refactor Bill widget

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#163]
Refactor on Bill widget according to:
https://xd.adobe.com/view/59df9aaa-9c2b-4d61-b839-5ea133aa39ec-0c8c/?fullscreen&hints=off
https://docs.google.com/presentation/d/1WpOQDLw-KJUEdW4-2kJSFpRewSjSKCc3XlGtjc0tXLY/edit#slide=id.p

**Comment by KipCrossing** [comment]
At this stage while filtering and tags are still being thought about. You can make the cards look like:

![Screenshot from 2020-12-24 11-54-29](https://user-images.githubusercontent.com/7298449/103047193-d0055a00-45de-11eb-819d-a7d08c4a42ce.png)
