### ISSUE TITLE
Apostrophes not rendering correctly in Android

### ISSUE THREAD

**Issue by okdaithi** [voteflux/voting_app#199]
Apostrophes don't render correctly in bill titles. (Screenshot attached)

Totally minor in scheme of things but probably important from an aesthetic point of view.

Device: LG G8 Android 10 & Android emulator Nexus 5 Android 11
 
![image](https://user-images.githubusercontent.com/16783415/105687609-9ef8ac00-5f33-11eb-8d39-6110dcf3b82e.png)

![image](https://user-images.githubusercontent.com/16783415/105687656-ac159b00-5f33-11eb-8e8f-ff6898db84ac.png)

**Comment by oscarmanderj** [comment]
This should be fixed on the API side before the data is added into the db.

@KipCrossing

**Comment by KipCrossing** [comment]
```dart
.replaceAll(new RegExp(r"[^\s\w()]"), "")
```

can be a quick fix
