### ISSUE TITLE
Generate public and private keys on first startup

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#24]
To do:
- Find a dart lib to Generate public and private keys on the first startup when name is entered on login page.
- wrap in function and write docs (for ctrl+q)
- Store private/public keys and name as [key-value data on disk](https://flutter.dev/docs/cookbook/persistence/key-value)
- logic for no login required *if* keys exist

**Comment by KipCrossing** [comment]
**Bonus:** Save app settings as key-value data (dark mode)

**Comment by KipCrossing** [comment]
From @ptboyer  04/17/2020
I'm not sure if a solution has been discussed recently about storing/retrieving private keys etc, but I'd recommend checking out: https://magic.link/ , if you haven't already. :) https://docs.magic.link/advanced/ethereum/get-started

**Comment by KipCrossing** [comment]
Noice!

@oscarmanderj found a really good NoSQL db https://github.com/hivedb/hive that we are likely to use to store the bills/issues/ results data. If it helps with how you are storing the keys, feel free to use.

**Comment by bazmatic** [comment]
Functions for key generation, storage, and retrieval is done. Next is the UI work.
