### ISSUE TITLE
fix mermaid github workflow

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#31]
not working for some reason

- using atm: https://github.com/neenjaw/compile-mermaid-markdown-action
- but maybe would be better: https://github.com/SimonKenyonShepard/mermaidjs-github-svg-generator

source: https://mermaid-js.github.io/mermaid/#/./integrations

**Comment by XertroV** [comment]
a workflow PR will trigger the live-updated workflow in that PR, I think...

**Comment by KipCrossing** [comment]
Closing as this is a "nice to have" and won't be on the critical path.

**Comment by XertroV** [comment]
> Closing as this is a "nice to have" and won't be on the critical path.

These are not reasons to close it. They are reasons not to keep it open. i.e., not to not close it. i.e., not _criticial_.

I don't think it's good to close tickets for this reason; the problem of diagrams and code being out of sync is still a problem.

**Comment by XertroV** [comment]
> Closing as this is a "nice to have" and won't be on the critical path.

Case in point: the Adrian's SC we are using atm is a nice to have and isn't on the critical path either...
