### ISSUE TITLE
task: github issue template for bug reports, etc

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#32]
(note: can use instabug et. al. for main/easy bug reports, but should do for github anyway)

* create an issue template for bug reports
* can use get-param on github issue creation URL to specify which template to use -- so can use with links or buttons or whatever
* issue template for feature requests too?
* other templates?

**Comment by KipCrossing** [comment]
Solution: https://www.instabug.com/integrations/github

**Comment by KipCrossing** [comment]
Let's see how the flow goes with Instabug -> GitHub issues 
No feature requests on GitHub, I'm calling it.
This discussion can be continued on #33
