### ISSUE TITLE
Lazy load bills

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#34]
We need a way to lazy load bills/issues on the all_bills_view.dart / all_issues_view.dart  

**Why:**
There are way too many bills to show on the view at once and has huge performance issues. I think the sweet spot for my device(s10) is around 20-30 bills painted on the view at once without any performance issues. Older devices might be worse.

**Possible ways:**
- Add cursor to api request and recall endpoint once page is scrolled to certain point
- Store all Bills in local storage state, then call from local storage adding them to the Bill list progressively. Then call the api once per day, or on app bootup.

**Comment by KipCrossing** [comment]
This has been fixed with https://medium.com/flutter-community/flutter-widget-guide-sliverlist-widget-in-5-mins-or-less-d1215c677388

in v 0.1.2
