### ISSUE TITLE
[BUG] PdfViewer stops showing file on orientation change

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#4]
PdfViewer stops showing file on orientation change

Perhaps there is a listener for orientation change and setState() can be invoked.

**Comment by ptboyer** [comment]
What's the status on this one?

Easiest solution could be to just lock orientation to portrait? and then open pdfs externally through mobile web browser (or new tab (web))?

**Comment by KipCrossing** [comment]
Still an issue: https://github.com/voteflux/voting_app/projects/1#card-34244115

It may be nice to have landscape mode to make it easier to read. I'm also in favour of the quick fix and landscape can be a feature request ;)

**Comment by ptboyer** [comment]
Yeah man, landscape mode is a definitely a luxury that can be included in the next version. Let's just get something out the door! ;)

**Comment by KipCrossing** [comment]
Settled! 

**Portrait only** <- for whoever picks up this card.
