### ISSUE TITLE
Upgrade charts

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#41]
Current graph package is only a pie chart

Because we need multiple different types of charts and to keep external packages to a minimum we need to upgrade the charts package to:

https://pub.dev/packages/charts_flutter#-readme-tab-

This will allow for multiple different chart types from same package.

**Comment by KipCrossing** [comment]
I think there is a card like this one that can be replaced.

Also, be sure to add labels, projects etc... --->
