### ISSUE TITLE
Get Ready for Alpha Distribution

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#44]
**anyone**:

- [x] gather docs on setting up testflight (ios)
- [x] gather docs on setting up pre-release via play store (android)
- [x] gather docs on code signing and config for ios: https://flutter.dev/docs/deployment/ios
- [x] gather docs on code signing and config for android: https://flutter.dev/docs/deployment/android

- [x] draft email to testers detailing instructions for iOS testlfight and android equiv
- [x] create release - https://github.com/voteflux/voting_app/releases

**iOS:** 
- [x] macos vm
- [x] macos flutter env
- [x] xcode server enabled for 'gitlab runner' user (do we need this? how to use?)
- [x] created a signing cert in xcode (todo: how to use / configure / add to apple dev / etc)
- [x] kip access to app store stuff / connect / whatever it's called
- [x] apple id created and things
- [x] 2fa + apple dev account setup (no app stuff, just dev account)
- [x] code signing keys set up and configured
- [x] App Store Connect
- [x] upload compiled app .ipa via Transporter
  - note: mk - had some trouble using transporter because apple ID doesn't have an itunes account or something; also couldn't log in to icloud (but could log in to app store as user); can we make an apple id into an icloud thing? do we want to?
- [x] test build approved/reviewed on testflight (submitted 4th may, approved 5th may)
- [x] load testers into app store connect / testflight
- [x] Distribute to testers via. TestFlight (tester downloads from App Store, developer distributes via App Store Connect, requires a yearly subscription with Apple Developer Program)
- [x] distribute email / links which is a referral code to be used in TestFlight (note: we don't get the code ourselves, we add them to a list and apple emails the code to them)

**Android:** 
- [x] Google Play Developer Console
- [x] Kip has admin for android
- [x] android build env
- [x] android code signing
- [x] upload compiled .apk via Console in a browser, create Alpha channel for application via console
- [x] load testers into google play (using `alpha` release channel)
- [x] test build approved/reviewed on play store (submitted 4th May)
- [x] distribute email / links to testers.

**Comment by XertroV** [comment]
We have an android dev account (with the _old_ flux app still in it) that i've given kip admin to

**Comment by KipCrossing** [comment]
Steps for android: https://flutter.dev/docs/deployment/android

Steps for iOS: https://flutter.dev/docs/deployment/ios

@XertroV

**Comment by XertroV** [comment]
macos flutter env:

```
~ ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── runner@Maxs-iMac-Pro 13:47:59 
❯ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-AU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by BenBallingall** [comment]
steps for setting up TestFlight: 
https://medium.com/@dmathewwws/steps-to-put-your-app-on-testflight-and-then-the-ios-app-store-10a7996411b1
https://developer.apple.com/videos/play/app-store-connect/101/

**Comment by oscarmanderj** [comment]
Pre-flight:
https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

**Comment by oscarmanderj** [comment]
Release
https://support.google.com/googleplay/android-developer/answer/7159011

**Comment by XertroV** [comment]
- flux foundation 'strike off' issue is ASIC not DUNS -- fixing
- applied for apple NFP dev account (we can't sell apps or have inapp purchases) -- application submitted; will just pay the dev fee if any issues

**Comment by XertroV** [comment]
app uploaded to testflight and google play

- in app store connect we need to add testers which _should_ then send them a link
- in google play we need to populate list of testers for alpha release then actually do the release

**Comment by BenBallingall** [comment]
i can't do this.

**Comment by BenBallingall** [comment]
have shared Alpha Tester response form with Max, Kipling & Nathan
Orange is Android, Green is Apple.

Please let me know when this has been actioned so i can begin Comms <3

**Comment by XertroV** [comment]
* google play testers set up by kip last night -- test build not yet reviewed by google
* app store access given to BenB for testers
* app store test build approved this morning (@TomSesselmann already installed) -- test list needs populating then it should email them (@BenBallingall add me as a test account if you want to double check the email gets delivered and you don't have requisite gear / iphone / whatever)

**Comment by BenBallingall** [comment]
- all Apple testers added to Testflight and should have received email and instructions how to download from Apple
- all Android Testers added to GooglePlay account, awaiting review of *DigiPol* testing build and instruction on how Alpha Testers access/download build

Apple testers are *unofficially* capable of testing and playing around with app right at this moment. Awaiting final build review from google play for Android test build to be released, then official testing timeline can begin.

Next steps stand as:

- Await GooglePlay contact that build is reviewed, with attached download link for *DigiPol* Android (1-7 days)
- Forward that link and install instruction to Android testers (1 day)
- Email entire Alpha Testing group with instructions and links for standard bug reporting/discussion format i.e; create GitHub account > lodge report via GitHub link > Discuss on Discord
