### ISSUE TITLE
Add Icon

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#58]
Probs don't want the flutter logo

**Comment by oscarmanderj** [comment]
should I just use the Flux logo?

**Comment by KipCrossing** [comment]
hang tight, one is on its way

**Comment by KipCrossing** [comment]
**Icon:** https://drive.google.com/open?id=18zVDWg2ncLRa0P-F9ui7Jds80WexxOiG

**Comment by KipCrossing** [comment]
https://medium.com/@psyanite/how-to-add-app-launcher-icons-in-flutter-bd92b0e0873a
and
https://stackoverflow.com/questions/49353199/how-to-change-the-app-display-name-build-with-flutter
