### ISSUE TITLE
make sure we have an easy screen to show debug and version info - needed for reports and if we update frequently thought testflight or whatever it'll be easy to lose track of.

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#59]
make sure we have an easy screen to show debug and version info - needed for reports and if we update frequently thought testflight or whatever it'll be easy to lose track of.

**Comment by oscarmanderj** [comment]
we could just include the version number on the settings page for now. WDYT?

**Comment by KipCrossing** [comment]
Yeah, that's a good idea. Can we also have a link to the GitHub issues page and a link to discord for bug reporting?

**Comment by KipCrossing** [comment]
Done in v 0.1.2
