### ISSUE TITLE
[BUG] the "you've voted" status icon in list of bills updates only after app closed

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#69]
The main list of bills didn't show a vote until i had closed and reopened the app -- the bill voting screen itself was fine (showed I had voted there)

**Comment by darragh11s** [comment]
This is happening on Samsung Galaxy S10+ on Android 10. After voting and closing the app, it says you voted in the list of bills but going into the bill allows me to vote again

**Comment by oscarmanderj** [comment]
@darragh11s  resolved v0.1.2

However, you are still able to vote again which just changes your vote.
