### ISSUE TITLE
[FEATURE REQ] Create filter to exclude issues/bills that have been voted on

### ISSUE THREAD

**Issue by TheITJuggler** [voteflux/voting_app#77]
**Describe the issue**
Viewing a list of bills/issues includes bills/issues that have already been voted on,.

**Requested behaviour**
UI to provide either a hamburger to select preference per bills/issue screen or a checkbox to set/unset preference to display voted on bills/issues
Cog to provide a way to set default preference to display voted on bills/issues

**Smartphone (please complete the following information):**
App Information:
App Name: DigiPol
App Version: 0.1.0 (0.1.0)
Installed App Version: 0.1.0 (0.1.0)

Device Information:
Device: iPhone12,5
iOS Version: 13.4.1
Language: en-AU (English (Australia))
Carrier: Telstra
Time zone: AEST
Architecture: arm64e
Connection Status: Wi-Fi
Paired Apple Watch: N/A

**Comment by KipCrossing** [comment]
This can be discussed in #63
