### ISSUE TITLE
[FEATURE REQ] "Date Updated" for bills/issues

### ISSUE THREAD

**Issue by TheITJuggler** [voteflux/voting_app#78]
**Describe the feature request**
There doesn't appear to be a way to `refresh' the listing of bills/issues while inside the app. It is also unclear if the list of bills/issues is refreshed at app start. 

**Expected behaviour**
Provide a timestamp of when bills/issues were last updated.

**Smartphone (please complete the following information):**
App Information:
App Name: DigiPol
App Version: 0.1.0 (0.1.0)
Installed App Version: 0.1.0 (0.1.0)

Device Information:
Device: iPhone12,5
iOS Version: 13.4.1
Language: en-AU (English (Australia))
Carrier: Telstra
Time zone: AEST
Architecture: arm64e
Connection Status: Wi-Fi
Paired Apple Watch: N/A

**Comment by KipCrossing** [comment]
This can be discussed in #68
