### ISSUE TITLE
hide coronavirus bills (temp soln)

### ISSUE THREAD

**Issue by XertroV** [voteflux/voting_app#79]
google is censoring anything that mentions coronavirus - need to filter bills to remove the 4+ that mention it currently.

I posted about it to /r/androiddev to see if anyone out there has ideas or feedback - https://www.reddit.com/r/androiddev/comments/gfgm2s/my_app_indexing_government_bills_was_suspended/

what I posted to discord last night:

> I suggest we implement a "censored" feature which does not hide the root UI elements of cards or issues, but renders the thing without any dynamic content and basically says  something like "due to censorship from [x] we are unable to show you this issue/bill. for more info see: [url]" and it's like rendered with the main background for the issue-card/page/whatever being red. In the code basically there's a censorship data struct with a party name, link for more info, and a list of banned words (in this case "coronavirus", "covid-19" at a minimum)
>
> so the user very clearly understands something is missing. because it's all decentralised we can have a website which shows the details as normal. also users should still be able to vote on the issue like normal, just that no details are shown

![image of the email from google](https://i.imgur.com/uLw1XO2.png)

**Comment by KipCrossing** [comment]
I can filter this on the API side and replace the text with whatever we want. Should I keep the pdfs in, I wonder? Or too risky?

**Comment by BenBallingall** [comment]
yeah, i wonder how the review process works? 
surely it's not got something scanning pdfs for words... but also, it's Google.

**Comment by KipCrossing** [comment]
These are the bills that contain "corona" OR "covid" in them:

```
('r6524', 'Appropriation (Coronavirus Economic Response Package) (No. 1) 2019-2020')
('r6530', 'Appropriation (Coronavirus Economic Response Package) (No. 2) 2019-2020')
('r6532', 'Appropriation (No. 5) 2019-2020')
('r6534', 'Appropriation (No. 6) 2019-2020')
('r6523', 'Assistance for Severely Affected Regions (Special Appropriation) (Coronavirus Economic Response Package) 2020')
('r6519', 'Australian Business Growth Fund (Coronavirus Economic Response Package) 2020')
('r6522', 'Boosting Cash Flow for Employers (Coronavirus Economic Response Package) 2020')
('r6521', 'Coronavirus Economic Response Package Omnibus 2020')
('r6535', 'Coronavirus Economic Response Package Omnibus (Measures No. 2) 2020')
('r6533', 'Coronavirus Economic Response Package (Payments and Benefits) 2020')
('r6529', 'Guarantee of Lending to Small and Medium Enterprises (Coronavirus Economic Response Package) 2020')
('r6528', 'Structured Finance Support (Coronavirus Economic Response Package) 2020')
```

I've filtered them out from updating and removed them from the DB as a quick fix.
