### ISSUE TITLE
[BUG] Choppy visual scrolling towards bottom of Bills list

### ISSUE THREAD

**Issue by connorhsm** [voteflux/voting_app#85]
**Describe the bug**
Bills interface becomes choppy when scrolling to the bottom of the list.

**To Reproduce**
Steps to reproduce the behaviour:
1. View to 'Bills' tab
2. Scroll down to the bottom of the list
3. Scroll slowly up and down through the list
4. Compared to similar scrolling actions whilst at the top of the list, you can notice a significant decrease in visual responsiveness/lag when scrolling.

**Expected behaviour**
I would expect the performance at the bottom of the list to be identical to the top of the list.

**Screenshots**
None

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS
 - Version: 13.3.1

**Additional context**
None

**Comment by XertroV** [comment]
@oscarmanderj does hive fix this?

**Comment by KipCrossing** [comment]
In the hive patch, @oscarmanderj Implemented [sliverlist](https://medium.com/flutter-community/flutter-widget-guide-sliverlist-widget-in-5-mins-or-less-d1215c677388).

Performance is really good now
