### ISSUE TITLE
[BUG] View Bill Text crashes the app

### ISSUE THREAD

**Issue by KipCrossing** [voteflux/voting_app#94]
**Describe the bug**
Clicking on *View Bill Text* and *View Explanatory Memoranda* Crashes the app

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a Bill Page
2. Click on View Bill Text
3. App crashes

**Expected behaviour**
Showing the contents of the bill text pdf

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android
 - Version 0.1.2

**Additional context**
@oscarmanderj This worked fine for me by building the debug version

**Comment by BenBallingall** [comment]
Seconded

Smartphone (please complete the following information):

Device: Huawei Mate 20 Pro
OS: Android
EMUI 10.0.0

**Comment by daolia** [comment]
Me too. 

Smartphone (please complete the following information):

Device: Pixel 3a
OS: Android
Version: 10

**Comment by gav0** [comment]
+1

Device: Asus Zenfone 6
OS: Android
Version: 10

**Comment by connorhsm** [comment]
Can not reproduce.
This functionality worked without issue when I originally tested some days ago and I can still use it as expected.

Device: iPhone 7
OS: iOS
Version: 13.4.1

**Comment by KipCrossing** [comment]
Looks like it's an android thing for now - we are about to push app version 0.1.2 to iOS soon. Let's see if you get the same then @connorhsm

**Comment by darragh11s** [comment]
Same thing happening Samsung galaxy S10+ Android 10

**Comment by KipCrossing** [comment]
Really strange:
iSO rejected v0.1.2
but
It works fine in debug mode

@oscarmanderj have you tried running it in production mode and testing?
