### ISSUE TITLE
Onboarding screens

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#98]
Need to implement maybe 3-4 on boarding screens explaining the app. This will greatly improve UX

Technical implementation is already complete just need relevant copy/illustrations

To do:

- [ ] Copy for 3-4 screens
- [ ] Find 3-4 illustrations [something like this](https://undraw.co/illustrations)

**Comment by KipCrossing** [comment]
Those illustrations are great! @BenBallingall have a look!

**Comment by BenBallingall** [comment]
Anyone got time for Discord tomorrow?
So I can pick your brains and sketch out what each page would need to contain/what info we need to share.

**Comment by okdaithi** [comment]
@BenBallingall hmu tonight or over the weekend and we'll get the structure and text sorted.

Started a doc here to get some ideas down.
https://docs.google.com/document/d/1oM1R6KISlxy7pD6UoC1hwiFsdXjyEDJ8jAaq7aLLywo/edit?usp=sharing

**Comment by BenBallingall** [comment]
Nice.
Yeah, I had a chat with Kip and drafted what needs to be on it. What we have currently, what we will have, etc.

Will get at you when I can ✊
