### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by oscarmanderj** [voteflux/voting_app#99]
Loading/splash screen needed so app isn't blank for 5s as it loads. Any suggestions/animations ?

**Comment by KipCrossing** [comment]
Flutter does widget animations. Perhaps we could use a few images from #98 with messages and shuffle through them

**Comment by XertroV** [comment]
https://voteflux.org/animated-logo.html

I made that for the first app (in early 2017)

**Comment by oscarmanderj** [comment]
great, will use this

**Comment by KipCrossing** [comment]
Are we wanting to use Flux branding upfront though? A strat question for @okdaithi @BenBallingall

**Comment by XertroV** [comment]
Is it not "digipol - by flux" (at least in essence even if the name on the app store isn't exactly that), like how little should we mention the reason we're doing it?

My feeling is a separate brand is important so it's more obvious that this isn't the parliament app; but we're only doing it to help us get to parliament, right?

**Comment by okdaithi** [comment]
Also was thinking - Digipol by Flux, or "made by / created by Flux"

Naming/branding like this is a good way/option for us to experiment with various iterations/scopes - but all the while making it clear this work is being done by Flux and is aligned with our core mission and objectives.

**Comment by BenBallingall** [comment]
![Screenshot_20200528_223358_com instagram android](https://user-images.githubusercontent.com/48424114/83141647-60f08180-a133-11ea-99c2-5eb0db4c3750.jpg)

Dis, but with some 3d grafx and the lion roar from MGM.

**Comment by oscarmanderj** [comment]
OK can't use that SVG directly. I didn't initially realise that it contains CSS animations. We need a pure SVG animation

**Comment by connorhsm** [comment]
Facebook's implementation is what also came to mind for me.
I put together some varients in Figma that you can see [here](https://www.figma.com/proto/GxS3EjOOx9FYWIruDmD4gs/DigiPol-Splash-Screens?node-id=22%3A124&scaling=scale-down).

Keep in mind this is only a quick draft, some other varients may include:

- Different wording and fonts/styles of the "Delivered by" and "From" text
- Removing the "VOTEFLUX ORG" line from the Flux logo
- Removing the Flux icon and only using the text "FLUX" with the broken X
- Removing the yellow background on the DigiPol icon and enlarging the other coloured elements of it
- Dark mode varient
- Any other thoughts

A preview:
![Screenshot_20200530_103322](https://user-images.githubusercontent.com/20902771/83315086-0c4b2480-a261-11ea-935f-0bae2604a71a.png)

**Comment by KipCrossing** [comment]
Done in #148
